#!/usr/bin/env bash

function put {
    builtin echo "$@"
}

function echoed_do {
    local cmd="$1"
    put "$(tput bold)$cmd$(tput sgr0)"
    eval "$cmd"
}

function do_reinstall {
    "$HOME/.nidus_site_config/nidus/install.sh"
}

function do_info {
    man nidus
}

function do_clean {
    rm -rf $HOME/.nidus_backup
}

function do_banner {
    local on_off="$1"
    local banner_file="$HOME/.nidus_site_config/bash/rc/49-banner.sh"
    local banner_disabled="$HOME/.nidus_site_config/bash/rc/.49-banner.sh.disabled"
    case "$on_off" in
        on)
            if [ -e "$banner_file" ]; then
                put "Already enabled."
                return 0
            fi
            if mv -f "$banner_disabled" "$banner_file" &>/dev/null; then
                put "Banner enabled."
            else
                put "Unable to enable banner."
            fi
            ;;
        off)
            if ! [ -e "$banner_file" ]; then
                put "Already disabled."
                return 0
            fi
            if mv -f "$banner_file" "$banner_disabled" &>/dev/null; then
                put "Banner disabled."
            else
                put "Unable to disable banner."
            fi
            ;;
        *)
            put "Please use on/off."
            return 1
            ;;
    esac
}

function do_update {
    echoed_do "cd '$HOME/.nidus_site_config/nidus'"
    echoed_do "git pull"
}

function print_usage {
    put "Usage: nidus subcommand"
    put "Subcommand:"
    put "    banner [ on | off ]    - turn on/off banner"
    put "    clean                  - delete backup directory"
    put "    info                   - alias of man nidus"
    put "    reinstall [ arg ... ]  - reinstall nidus"
    put "    update                 - update nidus"
}

function main {

    if [ $# -lt 1 ]; then
        print_usage
        return 1
    fi

    local subcommand="$1"
    shift

    case "$subcommand" in
        info)
            do_info
            ;;
        reinstall)
            do_reinstall "$@"
            ;;
        banner)
            do_banner "$@"
            ;;
        clean)
            do_clean
            ;;
        update)
            do_update
            ;;
        *)
            put "Invalid subcommand: $subcommand."
            print_usage
            return 1
    esac
}

main "$@"
