#!/bin/bash

set -euo pipefail

DIR=${1:-$(pwd)}

if [ "${DIR:0:1}" != / ]; then
    DIR="$(pwd)/$DIR"
fi

while :; do

    perm="$(stat -c %A "$DIR" 2>/dev/null)"
    if [ -z "$perm" ]; then
        perm="??????????"
    fi

    dev="$(df -P "$DIR" 2>/dev/null | tail -1 | cut -d' ' -f1)"
    if [ -z "$dev" ]; then
        dev="??????????"
    fi

    echo "$(tput setaf 3)$perm$(tput sgr0) $(tput setaf 2)$dev$(tput sgr0) $DIR"

    if [ "$DIR" = / ]; then
        break;
    fi

    DIR="$(dirname "$DIR")"

done
